name: dnclient

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup dnclient
        uses: quickvm/action-dnclient@v1
        with:
          dn-api-key: ${{ secrets.DN_API_KEY_ACTION_DNCLIENT }}
          dn-network-id: ${{ secrets.DN_NETWORK_ID_ACTION_DNCLIENT }}
          dn-role-id: ${{ secrets.DN_ROLE_ID_ACTION_DNCLIENT }}

      - name: Get the Host ID of the action
        shell: bash
        run: "sudo grep -F host_id /etc/defined/dnclient.yml |cut -d: -f2|xargs"

      - name: Send 10 pings to another host
        shell: bash
        run: ping -c 10 100.71.0.20
